spring:
  application:
    name: Car-Migo
  datasource:
    username: admin
    password: password
    url: jdbc:postgresql://localhost:5432/carmigo
  jpa:
    database-platform: carmigo
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC
        temp:
          use_jdbc_metadata_defaults: false

logging:
  level:
    web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "beans, health, info, metrics"
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: false

server:
  port: 8086

springdoc:
  api:
    description: RESTful API for CRUD operations on users (platform users, drivers and passengers) and journeys.
    title: Car-Migo API
  show-actuator: true
  swagger-ui:
    displayOperationId: true
    tagsSorter: alpha
  use-fqn: true
  writer-with-order-by-keys: true

---
spring:
  config:
    activate:
      on-profile: dev

debug: true

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://db:5432/carmigo
  devtools:
    add-properties: false
